# Multiple Linear Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('mlr.csv')

In [3]:
df

X1  X2     y
0   3   8  -3.7
1   4   5   3.5
2   5   7   2.5
3   6   3  11.5
4   2   1   5.7

In [5]:
x = df[['X1', 'X2']]

In [6]:
x

X1  X2
0   3   8
1   4   5
2   5   7
3   6   3
4   2   1

In [7]:
y = df[['y']]

In [8]:
y

y
0  -3.7
1   3.5
2   2.5
3  11.5
4   5.7

In [9]:
model = LinearRegression()

In [10]:
model.fit(x,y)

LinearRegression()

In [11]:
model.coef_

array([[ 2.28163009, -1.67210031]])

In [12]:
model.intercept_

array([2.79956113])

In [13]:
model.predict([[3,2]])

array([[6.30025078]])

In [15]:
sklearn_predict = model.predict(x)
sklearn_predict

array([[-3.7323511 ],
       [ 3.56557994],
       [ 2.5030094 ],
       [11.47304075],
       [ 5.690721  ]])

In [16]:
from sklearn.metrics import mean_squared_error